insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (101,139,0.6,9.7,false,false,false,'Jajko kurze',12.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (102,203,43.7,1.1,false,false,false,'Chleb pszenno-żytni',4.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (103,222,0.0,15.2,false,false,false,'Makrela wędzona',20.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (104,29,9.0,0.3,false,false,false,'Cytryna',1.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (105,97,16.7,1.5,false,false,false,'Koncentrat pomidorowy',5.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (106,4,0.5,0.0,false,false,false,'Herbata zielona (parzona)',0.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (107,86,3.5,0.2,false,false,false,'Twaróg chudy - Mlekopol',18.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (108,572,18.0,45.8,false,false,false,'Pestki dyni',24.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (109,124,26.5,0.5,false,false,false,'Makaron pełnoziarnisty (ugotowany)',5.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (110,50,4.7,2.0,false,false,false,'Kefir naturalny 2% tłuszczu',3.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (111,11,2.3,0.2,false,false,false,'Ogórek konserwowy',0.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (112,22,3.3,0.3,false,false,false,'Pieczarki świeże',3.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (113,264,4.1,21.3,false,false,false,'Ser Feta',14.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (114,61,4.8,3.2,false,false,false,'Mleko 3.2% tłuszczu',3.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (115,42,3.8,2.3,false,false,false,'Kiełki rzodkiewki',3.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (116,21,0.9,0.0,false,false,false,'Ocet jabłkowy',0.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (117,319,72.2,1.2,false,false,false,'Morele suszone',5.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (118,293,52.7,4.3,false,false,false,'Bułka kajzerka',9.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (119,17,3.0,0.1,false,false,false,'Roszponka',1.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (120,354,72.0,3.2,false,false,false,'Ryż brązowy (nieugotowany)',7.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (121,39,9.5,0.3,false,false,false,'Brzoskwinia',0.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (122,657,27.0,63.2,false,false,false,'Wiórki kokosowe',5.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (123,380,98.1,0.0,false,false,false,'Cukier brązowy',0.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (124,147,31.0,3.0,false,false,false,'Curry (potrawa)',4.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (125,2,0.3,0.0,false,false,false,'Kawa (rozpuszczona)',0.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (126,325,55.8,14.0,false,false,false,'Przyprawa Curry',14.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (127,0,0.0,0.0,false,false,false,'Zioła prowansalskie',0.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (128,101,27.4,0.1,false,false,false,'Ketchup',1.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (129,282,54.0,12.9,false,false,false,'Papryka słodka (proszek)',14.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (130,51,11.0,0.2,false,false,false,'Proszek do pieczenia',1.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (131,376,62.4,7.2,false,false,false,'Płatki owsiane górskie',11.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (132,111,1.3,3.3,false,false,false,'Polędwica sopocka - Morliny',19.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (133,884,0.0,100.0,false,false,false,'Olej',0.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (134,351,64.0,10.0,false,false,false,'Rozmaryn suszony',4.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (135,2,0.0,0.2,false,false,false,'Kawa Espresso',0.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (136,92,19.9,0.6,false,false,false,'Kasza gryczana (ugotowana)',3.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (137,199,38.0,1.0,false,false,false,'Chleb razowy - Oskroba',7.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (138,282,49.7,14.3,false,false,false,'Papryka chili (proszek)',13.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (139,96,0.0,3.0,false,false,false,'Szynka',17.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (140,262,54.3,1.4,false,false,false,'Chleb pszenny',8.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (141,18,2.3,0.1,false,false,false,'Sałata mix',0.8,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (142,69,18.1,0.2,false,false,false,'Winogrona zielone',0.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (143,104,4.2,1.7,false,false,false,'Indyk (pierś bez skóry)',17.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (144,19,5.9,0.0,false,false,false,'Ocet winny',0.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (145,313,75.0,8.4,false,false,false,'Liść laurowy suszony',7.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (146,19,4.3,0.1,false,false,false,'Kapusta kiszona',0.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (147,90,1.9,0.7,false,false,false,'Wędlina z piersi indyka',19.1,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (148,130,28.2,0.3,false,false,false,'Ryż biały (ugotowany)',2.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (149,17,2.6,0.4,false,false,false,'Pieczarka świeża',2.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (150,27,6.3,0.2,false,false,false,'Papryka żółta',1.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (151,271,58.3,1.4,false,false,false,'Bułka pszenna',7.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (152,35,7.2,0.4,false,false,false,'Brokuły (gotowane bez soli)',2.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (153,247,41.3,3.4,false,false,false,'Chleb pszenny razowy',13.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (154,60,15.0,0.4,false,false,false,'Mango',0.8,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (155,167,1.6,9.0,false,false,false,'Ser Mozzarella light - Galbani',20.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (156,23,1.0,0.5,false,false,false,'Kiełki lucerny',4.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (157,126,2.0,4.8,false,false,false,'Szynka z indyka - Coop',18.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (158,114,15.8,1.1,false,false,false,'Fasola czerwona (konserwa) - Red Kidney',7.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (159,32,8.1,0.1,false,false,false,'Grejpfrut',0.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (160,232,1.0,18.1,false,false,false,'Szynka wieprzowa z tłuszczem. gotowana',16.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (161,85,1.5,1.6,false,false,false,'Szynka z piersi kurczaka (delikatna)',16.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (162,33,3.0,1.4,false,false,false,'Kawa Latte',2.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (163,143,0.0,10.0,false,false,false,'Jajko ugotowane na miękko',12.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (164,282,49.7,14.3,false,false,false,'Papryka ostra (proszek)',13.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (165,22,0.4,0.9,false,false,false,'Szpinak BABY surowy',2.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (166,535,50.3,35.3,false,false,false,'Gałka muszkatołowa (mielona)',6.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (167,14,3.0,0.2,false,false,false,'Seler (natka)',0.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (168,273,61.0,4.6,false,false,false,'Otręby pszenne',17.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (169,452,0.1,32.0,false,false,false,'Ser Parmezan',41.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (170,30,7.6,0.2,false,false,false,'Arbuz',0.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (171,331,70.0,7.0,false,false,false,'Kardamon',11.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (172,50,13.1,0.1,false,false,false,'Ananas',0.5,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (173,49,4.7,2.0,false,false,false,'Mleko 2% tłuszczu - Mlekovita',3.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (174,365,79.0,1.4,false,false,false,'Ryż parboiled długoziarnisty (nieugotowany) - Biedronka',7.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (175,364,76.3,1.0,false,false,false,'Mąka pszenna typ 500',10.3,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (176,67,4.2,4.4,false,false,false,'Surówka Colesław',0.8,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (177,43,9.6,0.2,false,false,false,'Burak',1.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (178,155,1.1,10.6,false,false,false,'Jajko kurze gotowane',12.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (179,340,58.0,3.2,false,false,false,'Makaron pełnoziarnisty Pióra (nieugotowany)',15.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (180,35,7.5,0.0,false,false,false,'Pomidory w puszce',1.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (181,150,3.5,8.5,false,false,false,'Ser Feta light Apetina - Arla',16.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (182,50,11.8,0.2,false,false,false,'Nektarynka',0.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (183,149,1.6,11.0,false,false,false,'Jajecznica',10.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (184,125,1.0,7.5,false,false,false,'Serek homogenizowany naturalny - Pilos',11.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (185,31,7.1,0.1,false,false,false,'Fasolka szparagowa (żółta)',1.8,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (186,45,4.8,1.5,false,false,false,'Mleko 1.5%',3.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (187,32,7.3,0.2,false,false,false,'Dymka cebula',1.8,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (188,331,64.0,15.5,false,false,false,'Rozmaryn suszony (proszek)',4.9,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (189,16,3.2,0.2,false,false,false,'Kapusta pekińska',1.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (190,50,5.0,2.0,false,false,false,'Mleko 2%',3.0,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (191,155,1.1,10.6,false,false,false,'Jajko gotowane',12.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (192,44,4.5,1.5,false,false,false,'Kefir naturalny gęsty 1.5% tłuszczu - Tola',3.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (193,553,30.2,43.9,false,false,false,'Orzechy nerkowca',18.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (194,23,2.7,0.6,false,false,false,'Bazylia - liście',3.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (195,138,5.1,7.9,false,false,false,'Ser Ricotta (częściowo odtłuszczony)',11.4,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (196,211,41.5,1.6,false,false,false,'Chleb razowy 100% żytni',4.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (197,363,75.6,2.2,false,false,false,'Bułka tarta',9.2,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (198,680,3.0,74.0,false,false,false,'Majonez',0.6,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (199,375,67.6,6.3,false,false,false,'Płatki owsiane błyskawiczne',12.7,1);
insert into ingredient (id,calories, carbohydrates,fats,has_gluten,has_lactose,has_meat,name,proteins,unit) values (200,103,0.0,0.8,false,false,false,'Tuńczyk w sosie własnym - Calvo',24.0,1);
