drop table loan IF EXISTS;

create table loan (
loan_number bigint generated by default as identity,
amount_paid numeric(19,2),
create_at varchar(255), 
customer_id bigint,
loan_type varchar(255), 
outstanding_amount numeric(19,2), 
start_at date, 
total_loan numeric(19,2), 
primary key (loan_number)
);