drop table account IF EXISTS;
drop table customer IF EXISTS;

create table account (
account_number bigint not null, 
account_type varchar(255), 
branch_address varchar(255), 
created_at date, 
customer_id bigint, 
primary key (account_number)
);

create table customer (
id bigint generated by default as identity,
created_at date, 
email varchar(255), 
mobile_number varchar(255), 
name varchar(255), 
primary key (id)
);
