drop table card IF EXISTS;

create table card (
card_id bigint generated by default as identity,
amount_used numeric(19,2),
available_amount numeric(19,2), 
card_number varchar(255), card_type varchar(255), 
create_dt date,
customer_id bigint, 
total_limit numeric(19,2),
primary key (card_id)
);